<?php

namespace ProjectBundle\Repository;

use Doctrine\ORM\Query;

/**
 * ControleForceBruteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ControleForceBruteRepository extends \Doctrine\ORM\EntityRepository
{
    public function compteIp($ip, $dateBefore)
    {
        $qb = $this->createQueryBuilder('C')
            ->where ('C.ip = :ip')
            ->andWhere('C.date > :date')
            ->setParameter('ip', $ip)
            ->setParameter('date', $dateBefore)
            ->getQuery()->getResult();

        return $qb;
    }
    public function getDate($ip){
        $qb = $this->createQueryBuilder('C')
            ->select('MAX(C.date)')
            ->where ('C.ip = :ip')
            ->setParameter('ip', $ip)
            ->getQuery()->getSingleScalarResult();

        return $qb;
    }
}
