<?php

namespace ProjectBundle\Repository;

use Doctrine\ORM\Query;

/**
 * ControleForceBruteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ControleForceBruteRepository extends \Doctrine\ORM\EntityRepository
{
    public function compteIp($ip, $date, $dateBefore)
    {
        $qb = $this->createQueryBuilder('C')
            ->where ('C.ip = :ip')
            ->andWhere('C.date BETWEEN :date2 and :date1')
            ->setParameter('ip', $ip)
            ->setParameter('date1', $date)
            ->setParameter('date2', $dateBefore)
            ->getQuery()->getResult();

        return $qb;
    }
    public function getDate($ip){
        $qb = $this->createQueryBuilder('C')
            ->where ('C.ip = :ip')
            ->orderBy('C.date', 'DESC')
            ->setParameter('ip', $ip)
            ->getQuery()->get();

        return $qb;
    }
}
