<?php

namespace ProjectBundle\Repository;

/**
 * EntrepriseTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntrepriseTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
