<?php

namespace ProjectBundle\Repository;

/**
 * PromoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromoRepository extends \Doctrine\ORM\EntityRepository
{
}
