<?php

namespace ProjectBundle\Repository;

/**
 * TechnologieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TechnologieRepository extends \Doctrine\ORM\EntityRepository
{
}
